### PR TITLE
fix(db): update for new DB schema

### PR DESCRIPTION
**Pull request by JeanBarriere**
- [x] update create_owner_by_login function
- [x] remove usage of owner_vcs

---
blocked by [#161](https://github.com/storyscript/database/pull/161)

### CODE REVIEW

**Comment by JeanBarriere** [comment]
@williammartin I don't understand why the tests are failing. They should not

**Comment by williammartin** [comment]
@JeanBarriere Did they pass locally?

**Comment by JeanBarriere** [comment]
I didn't launched them locally 🌞

**Comment by williammartin** [comment]
They pass locally for me. On CI they appear to be failing because SameSite is a string, when Agouti expects it to be an int:

https://github.com/storyscript/auth/pull/6/checks?check_run_id=450337894#step:6:48

**Comment by williammartin** [comment]
I upgraded chromdriver locally to `80.0.3987.106` and now see this error:

image

**Comment by williammartin** [comment]
This is a failure with one of our vendored dependencies (agouti) that I accidentally changed to handle samesite values (but did it badly). I'm going to merge this and follow up with a commit that will fix the tests, as it's easier to do it that way than vice versa with changes to the database schema on the latest docker image.

**Comment by williammartin** [comment]
Fixed in https://github.com/storyscript/auth/commit/91b886d0c8766006aef6b13b7a7a9384f8411952 and created a Tracker chore to get agouti updated to properly handle samesite values: https://www.pivotaltracker.com/story/show/171309646

**Pull request merged**
